#!/bin/bash

HW=proj3
SOURCEDIR=/comp/15/files/$HW
LINKDIR=$SOURCEDIR/.DONT_COPY

##
## Make sure student is in a directory named for assignment
## or that they are ok putting stuff in whatever directory they are
## in.
##
HERE=$(pwd)
CURRDIR=$(basename $HERE)
if test $CURRDIR != "$HW"
then
	printf "About to put $HW material into $HERE\n"
	printf "Is that ok?  (y/n):  "
	read RESPONSE
	case "$RESPONSE" in
	     y*|Y*)                                    ;;
	     *)	      echo "OK then.  Aborting..."
	     	      exit 1                           ;;
	esac
fi

##
## Copy over files except those in the link directory
## Assuming link directory starts with a . so I don't
## have to filter it out.
##
## Don't copy backup files or the setup script itself
##

for file in $SOURCEDIR/*
do
    case "$(basename $file)" in
	*~)                      ;;  # skip editor backups
	setup)                   ;;  # students don't need the script
        setup_links)             ;;  # they don't need the old setup script
	*)       cp -i $file ./  ;;  # ask before overwriting!
    esac
done

##
## Just link things in the link directory
## If there were files to copy, then we'd have to do that, too
##
for file in $LINKDIR/*
do
    ln -s $file ./
done
